# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            'James Hibbard'
tagline:          'Web Developer'
description:      'Web developer, network admin and author'
url:              https://hibbard.eu
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

analytics: true
comments: true
disqus:
  shortname: james-hibbard

author:
  name:           'James Hibbard'
  url:            https://twitter.com/jchibbard

paginate:         10
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-onebox

# Custom vars
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/jameshibbard/blog
